### ISSUE TITLE
Does not work if issue key is only thing in text

### ISSUE THREAD

**Issue by TheRealWaldo** [cybervoid/gajira-get-issue#2]
Seems to not work if the text contains ONLY the issue key.

```
    - name: Find Jira Issue
      uses: cybervoid/gajira-get-issue@v1.1
      with:
        input-text: HA-33
```
Fails to find the issue key.
